export const projects = [
  {
    name: "Code Dojo",
    description:
      "Code Dojo is a real-time collaborative coding platform where users can create and join coding rooms. It supports multiple programming languages and provides features like live code editing, code execution, and room management.",
    challenge: [
      "Develop a platform enabling real-time code collaboration and execution.",
      "Implement secure user authentication for both public and private coding rooms.",
      "Ensure a seamless and intuitive interface for users across multiple devices.",
      "Integrate support for multiple programming languages and manage efficient communication between the frontend and backend.",
    ],
    solution: [
      "Built the frontend with React, TypeScript, and Vite for modularity and performance.",
      "Implemented real-time code synchronization using Yjs and Socket.IO.",
      "Integrated Monaco Editor for a robust coding experience, styled with NextUI and Tailwind CSS.",
      "Secured authentication with JWT and structured the backend with Node.js, Express.js, and PostgreSQL using Drizzle ORM.",
      "Used the Judge0 API for executing and displaying code output, providing seamless multi-language support.",
    ],
    technologies: [
      "TypeScript",
      "React.js",
      "TailwindCSS",
      "Node.js",
      "Express",
      "PostgreSQL",
      "DrizzleORM",
      "Socket.IO",
    ],
    skills: [
      "Frontend Architecture",
      "UI/UX & Responsiveness",
      "Real-Time Features",
      "Backend Development",
      "Database Design & Management",
      "Authentication & Authorization",
      "Git & Version Control",
    ],
    repository: "https://github.com/martinablazheska/code-playground",
    images: [
      "projects/code-dojo/unauthenticated.png",
      "projects/code-dojo/login.png",
      "projects/code-dojo/create-room.png",
      "projects/code-dojo/join-room.png",
      "projects/code-dojo/execute-code.png",
    ],
  },
  {
    name: "Promovere",
    description:
      "Promovere Garment Configurator is a platform that allows users to customize garments by selecting colors and decorations, with a 3D preview feature. It includes role-based access control, advanced search capabilities, and a responsive design to ensure a smooth experience across devices. The platform balances complex functionality with user-friendly features.",
    challenge: [
      "Improve an existing application with features like infinite scroll and filtering for a large product catalog.",
      "Set up MeiliSearch to handle a wide range of filters efficiently.",
      "Implement role-based authentication using Keycloak, integrated with Strapi and NextAuth.",
      "Extend Strapi's users & permissions plugin to meet specific business needs.",
      "Ensure robust error handling on both the frontend and backend.",
      "Optimize the app for better performance and speed.",
    ],
    solution: [
      "Enhanced the existing Next.js frontend with Tailwind CSS for responsiveness.",
      "Added infinite scroll and configured MeiliSearch for fast, flexible filtering.",
      "Integrated Keycloak with Strapi and NextAuth for secure and complex authentication.",
      "Overrode and extended Strapi's users & permissions plugin to support custom requirements.",
      "Implemented detailed error handling across the frontend and backend for better reliability.",
      "Optimized performance by addressing key bottlenecks and improving scalability.",
    ],
    technologies: [
      "TypeScript",
      "Next.js",
      "TailwindCSS",
      "Node.js",
      "meilisearch",
      "Strapi",
      "Apollo GraphQL",
      "Keycloak",
    ],
    skills: [
      "Frontend Architecture",
      "UI/UX & Responsiveness",
      "React Optimization",
      "Backend Development",
      "Strapi Customization",
      "Authentication & Authorization",
      "Git & Version Control",
    ],
    deployment: "https://promovere-web.vercel.app/",
    images: [
      "projects/promovere/product-details-page.png",
      "projects/promovere/browse-garments.png",
      "projects/promovere/dashboard.png",
      "projects/promovere/company-profile.png",
      "projects/promovere/invite-user.png",
      "projects/promovere/user-profile.png",
    ],
  },
];
